### PR TITLE
Seperate gps_msg from Postion Data

### PR DESCRIPTION
**Pull request by willdzeng**
Before when we have pos data from the device, we use the same topic as the raw gps data, this causes an issue if one just want to use the raw data or the filtered data, also what I noticed is that the filtered data often has different altitude. so it's better to have them separated.

### CODE REVIEW

**Comment by fcolas** [comment]
Many thanks for your contribution. I have a single issue about the topic names.
The convention for ROS drivers of GPS devices is to publish the `NavSatFix` message on the `fix` topic.
As `RAWGPS` is a legacy message, I'd suggest using `raw_fix` for `RAWGPS` and keep `fix` for `Position` information.
Could you please made the corresponding changes in your pull request, thanks.

**Comment by willdzeng** [comment]
Done! thanks.

**Comment by fcolas** [comment]
Actually, I'm not sure which one should be the main one (`/fix`) between GNSS PVT and the filtered one. But as long as it is explicit in the documentation, it's ok.
By the way, sorry to have forgotten, could you update the documentation in `mainpage.dox` to reflect this change?

**Comment by willdzeng** [comment]
Done, I think making the filtered gps default is better, the unfiltered one is not very useful.

**Comment by fcolas** [comment]
Many thanks!

**Pull request merged**
